#!/usr/bin/env node

const swaggerJsdoc = require('swagger-jsdoc');
const fs = require('fs');
const path = require('path');

// Import the swagger configuration
const swaggerConfig = require('../swagger-config.js');

console.log('🔍 Generating Swagger documentation...');

try {
  // Generate the Swagger specification
  const specs = swaggerJsdoc(swaggerConfig);

  // Write the specification to a JSON file
  // eslint-disable-next-line no-undef
  const outputPath = path.join(__dirname, '..', 'swagger.json');
  fs.writeFileSync(outputPath, JSON.stringify(specs, null, 2));

  // Generate the TypeScript constant for the API route
  // eslint-disable-next-line no-undef
  const tsOutputPath = path.join(__dirname, '..', 'src', 'spec', 'swagger-spec.ts');
  const tsContent = `// Auto-generated Swagger specification
// This file is generated by scripts/generate-swagger.js
// Do not edit manually

export const swaggerSpec = ${JSON.stringify(specs, null, 2)} as const;

export default swaggerSpec;
`;

  fs.writeFileSync(tsOutputPath, tsContent);

  console.log('✅ Swagger documentation generated successfully!');
  console.log(`📄 JSON specification saved to: ${outputPath}`);
  console.log(`📄 TypeScript specification saved to: ${tsOutputPath}`);
  console.log(`🌐 You can view it at: http://localhost:8081/api/docs`);
  console.log(`📊 Total endpoints documented: ${Object.keys(specs.paths || {}).length}`);

  // Log the documented endpoints
  if (specs.paths) {
    console.log('\n📋 Documented endpoints:');
    Object.keys(specs.paths).forEach((path) => {
      const methods = Object.keys(specs.paths[path]);
      methods.forEach((method) => {
        const endpoint = specs.paths[path][method];
        console.log(`  ${method.toUpperCase()} ${path} - ${endpoint.summary || 'No summary'}`);
      });
    });
  }

  console.log('\n🔄 Next steps:');
  console.log('1. The swagger-spec.ts file has been updated');
  console.log('2. The swagger.json+api.ts route will now use the generated specification');
  console.log('3. Restart your development server to see the changes');
} catch (error) {
  console.error('❌ Error generating Swagger documentation:', error);
  process.exit(1);
}
